# coding: utf-8

from __future__ import annotations
from datetime import date, datetime  # noqa: F401

import re  # noqa: F401
from typing import Any, Dict, List, Optional  # noqa: F401

from pydantic import AnyUrl, BaseModel, EmailStr, Field, validator  # noqa: F401


class TokenVoteData(BaseModel):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.

    TokenVoteData - a model defined in OpenAPI

        name: The name of this TokenVoteData [Optional].
        symbol: The symbol of this TokenVoteData [Optional].
        icon_url: The icon_url of this TokenVoteData [Optional].
        votes: The votes of this TokenVoteData [Optional].
    """

    name: Optional[str] = Field(alias="name", default=None)
    symbol: Optional[str] = Field(alias="symbol", default=None)
    icon_url: Optional[AnyUrl] = Field(alias="iconUrl", default=None)
    votes: Optional[int] = Field(alias="votes", default=None)

    model_config = {
        "json_schema_extra": {
            "example": {
                "name": "Scale",
                "symbol": "SCALE",
                "iconUrl": "https://cache.tonapi.io/imgproxy/jHx0m3tMBFj9z9vLy1cooH_v8DIi_2Zi43RLxyfga3g/rs:fill:200:200:1/g:no/aXBmczovL1FtU01pWHNaWU1lZndyVFEzUDZIbkRRYUNwZWNTNEVXTHBnS0s1RVgxRzhpQTg.webp",
                "votes": 111000,
            },
        }
    }


TokenVoteData.model_rebuild()
